apiVersion: apps/v1
kind: Deployment
metadata:
  name: pare-azul-junior
  namespace: viptech
  labels:
    app: pare-azul-junior
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pare-azul-junior
  template:
    metadata:
      labels:
        app: pare-azul-junior
    spec:
      containers:
        - name: pare-azul-junior
          image: juca266/pare-azul-junior:latest
          ports:
            - containerPort: 4000
          env:
            - name: TZ
              value: America/Sao_Paulo
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime